package main

/*

import (
	"math/rand"
	"os"

	"github.com/go-echarts/go-echarts/v2/charts"
	"github.com/go-echarts/go-echarts/v2/opts"
)

// generate random data for bar chart
func generateBarItems() []opts.BarData {
	items := make([]opts.BarData, 0)
	for i := 0; i < 7; i++ {
		items = append(items, opts.BarData{Value: rand.Intn(300)})
	}
	return items
}

func runVisualization() {
	dailyValues, err := visualizationTest_queryForDailyCalories()
	if err != nil {
		handleError(err, "Issue grabbing daily calorie info")
	}


	// create a new bar instance
	bar := charts.NewBar()
	// set some global options like Title/Legend/ToolTip or anything else
	bar.SetGlobalOptions(charts.WithTitleOpts(opts.Title{
		Title:    "My first bar chart generated by go-echarts",
		Subtitle: "It's extremely easy to use, right?",
	}))

	dateList := make([]string, 0)
	calorieList := make([]opts.BarData, 0)
	for _, row := range dailyValues {
		dateList = append(dateList, row.date)
		calorieList = append(calorieList, opts.BarData{Value: row.calories})
	}

	bar.SetXAxis(dateList).
		AddSeries("Calories", calorieList)
	// Put data into instance
	f, _ := os.Create("bar.html")
	bar.Render(f)
}
*/